- name: Facts and magic variables lab
  hosts: workers
  gather_facts: yes   # turn facts ON

  tasks:
    - name: Show host info
      debug:
        msg:
          - "Inventory name: {{ inventory_hostname }}"
          - "OS hostname: {{ ansible_facts['hostname'] }}"
          - "OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
          - "IP: {{ ansible_facts['default_ipv4']['address'] }}"

